// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKtV6otrHaUPwgCdRFV4uONIUmG565ZDc',
    appId: '1:194173261522:web:8ae94ea01ab796cab4ff0b',
    messagingSenderId: '194173261522',
    projectId: 'fir-32-hw',
    authDomain: 'fir-32-hw.firebaseapp.com',
    storageBucket: 'fir-32-hw.firebasestorage.app',
    measurementId: 'G-HSQW4XJBRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ0SrUAqcvK0XESCowYkHHXfxlZrDZGmI',
    appId: '1:194173261522:android:71b78c05294cc2fbb4ff0b',
    messagingSenderId: '194173261522',
    projectId: 'fir-32-hw',
    storageBucket: 'fir-32-hw.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYfQ6PUUfGjbPiHeG_Limt7ZZxXALGajM',
    appId: '1:194173261522:ios:3584cc86a7abc986b4ff0b',
    messagingSenderId: '194173261522',
    projectId: 'fir-32-hw',
    storageBucket: 'fir-32-hw.firebasestorage.app',
    iosBundleId: 'com.example.firebase32',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYfQ6PUUfGjbPiHeG_Limt7ZZxXALGajM',
    appId: '1:194173261522:ios:3584cc86a7abc986b4ff0b',
    messagingSenderId: '194173261522',
    projectId: 'fir-32-hw',
    storageBucket: 'fir-32-hw.firebasestorage.app',
    iosBundleId: 'com.example.firebase32',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKtV6otrHaUPwgCdRFV4uONIUmG565ZDc',
    appId: '1:194173261522:web:e620f4fd45a02cb1b4ff0b',
    messagingSenderId: '194173261522',
    projectId: 'fir-32-hw',
    authDomain: 'fir-32-hw.firebaseapp.com',
    storageBucket: 'fir-32-hw.firebasestorage.app',
    measurementId: 'G-LC4FH3WCLP',
  );
}
